In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
x=[1,2,3,4,5,6]
type(x)

list

In [8]:
arr = np.array(x)  
print(arr)

[1 2 3 4 5 6]


In [9]:
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
type(arr)

numpy.ndarray

In [11]:
np.arange(1,14) // //(initialization, till-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [16]:
np.arange(1,14,3) //(initialization, till-1, gaps between every value)

array([ 1,  4,  7, 10, 13])

In [19]:
np.zeros((2,4)) // Give definite zeros in the form of rows and columns.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3,6)) // Give definite ones in the form of rows and columns.

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr1 = np.random.randint(10,1000,30) // As it named as random it will give us random values everytime we run.
print(arr1)

[102 384 983 559 251 175 803 968 393 650 149 492 699  96 725 950 957 322
 237  75  59 696 159 478  88 577 358 233 364  77]


In [31]:
np.random.seed(31) // It is use for a constant value 
arr1 = np.random.randint(10,1000,30)
print(arr1)

[732 609  26 904 620 673 836  38 262 743 752 614 900 436 824 784 348 668
 776  35 603 929 629 422 763 660 379 734 132 694]


In [34]:
arr2 = np.random.randint(0,1000,30)
print (arr2)

[521 388 709 632 308 298 875 498 440 178 954  16 858 995 862 513 437 331
 467 892 363 402 731 158 773  60 662 262 189 148]


In [52]:
arr1.reshape(3,10) // We can modify our array in R & C form.

array([[732, 609,  26, 904, 620, 673, 836,  38, 262, 743],
       [752, 614, 900, 436, 824, 784, 348, 668, 776,  35],
       [603, 929, 629, 422, 763, 660, 379, 734, 132, 694]], dtype=int32)

In [53]:
arr1.max()

np.int32(929)

In [57]:
arr1.min()

np.int32(26)

In [58]:
arr1.mean()

np.float64(584.1666666666666)

In [59]:
arr2.argmin() // min value index value

np.int64(11)

In [60]:
arr2.argmax()

np.int64(13)

In [61]:
arr2.max()

np.int32(995)

In [62]:
arr1.shape // To get the shape of array

(30,)